# Generated by Django 4.0.4 on 2022-04-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryrule',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_factory_rule_profile', to='account.profile', verbose_name='创建人'),
        ),
    ]
