# Generated by Django 4.0.4 on 2022-04-21 11:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.MinLengthValidator(limit_value=13)], verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recommender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_recommender', to=settings.AUTH_USER_MODEL),
        ),
    ]
