# Generated by Django 4.0.4 on 2022-04-25 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_factoryrule_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryrule',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_factory_rule_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
