# Generated by Django 4.0.4 on 2022-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_mobile_profile_recommender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cam_level',
            field=models.CharField(blank=True, choices=[('level1', '等级1'), ('level2', '等级2'), ('level3', '等级3'), ('level4', '等级4'), ('level5', '等级5')], default='level1', max_length=10, null=True),
        ),
    ]
