# Generated by Django 4.0.4 on 2022-10-18 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='车厢名称')),
                ('remark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注')),
                ('carriage_type', models.CharField(blank=True, choices=[('head', '车头'), ('mid', '中间'), ('tail', '车尾')], default='head', max_length=10, null=True, verbose_name='车厢类型')),
                ('carriage_use', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='车厢用途')),
                ('check_set', models.CharField(blank=True, choices=[('no', '无需审核'), ('yes', '需要审核')], default='no', max_length=10, null=True, verbose_name='是否需要审核')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_carriage_author_check_user', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('author_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_carriage_author_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('author_exe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_carriage_author_exe_user', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'db_table': 'process_carriage',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='火车名称')),
                ('remark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注')),
                ('train_use', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='火车用途')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('train_author_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_train_author_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'process_train',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='TrainSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_current', to='process.carriage', verbose_name='当前车厢')),
                ('current_carriage_author_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_current_carriage_author_create', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('post_carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_post', to='process.carriage', verbose_name='下一节车厢')),
                ('pre_carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_pre', to='process.carriage', verbose_name='上一节车厢')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_for_train', to='process.train', verbose_name='归属火车')),
            ],
            options={
                'db_table': 'process_train_set',
                'ordering': ('order_id',),
            },
        ),
    ]
