# Generated by Django 4.0.4 on 2022-05-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='author_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_carriage_author_check_user', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
