# Generated by Django 4.0.4 on 2022-05-03 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0003_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='备注')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_current', to='process.carriage', verbose_name='当前车厢')),
                ('current_carriage_author_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_current_carriage_author_create', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('post_carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_post', to='process.carriage', verbose_name='下一节车厢')),
                ('pre_carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_train_set_pre', to='process.carriage', verbose_name='上一节车厢')),
            ],
            options={
                'db_table': 'process_train_set',
                'ordering': ('-publish',),
            },
        ),
    ]
