# Generated by Django 4.0.4 on 2022-05-03 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_trainset_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='车厢名称'),
        ),
        migrations.AlterField(
            model_name='carriage',
            name='remark',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='火车名称'),
        ),
        migrations.AlterField(
            model_name='train',
            name='remark',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_use',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='火车用途'),
        ),
        migrations.AlterField(
            model_name='trainset',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='trainset',
            name='remark',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注'),
        ),
    ]
