# Generated by Django 4.0.4 on 2022-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_alter_carriage_name_alter_carriage_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainset',
            name='order_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
    ]
