# Generated by Django 4.0.4 on 2022-05-04 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_trainset_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainset',
            options={'ordering': ('order_id',)},
        ),
        migrations.AlterField(
            model_name='carriage',
            name='carriage_use',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='车厢用途'),
        ),
    ]
