# Generated by Django 3.2.13 on 2022-04-16 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_odb', models.FileField(upload_to='router_job_odb', verbose_name='ODB++(.tgz)')),
                ('file_compressed', models.FileField(upload_to='router_job_compressed', verbose_name='原始资料（压缩包）')),
                ('job_name', models.CharField(max_length=250, verbose_name='料号名称')),
                ('slug', models.SlugField(max_length=250, unique_for_date='receive_date')),
                ('receive_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='接受料号时间')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipe_status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='是否提供了参数')),
                ('remark', models.TextField(verbose_name='备注')),
                ('receive_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_org', to=settings.AUTH_USER_MODEL, verbose_name='料号负责人')),
            ],
            options={
                'verbose_name': '料号',
                'verbose_name_plural': '料号',
                'ordering': ('-receive_date',),
            },
        ),
    ]
