# Generated by Django 3.2.13 on 2022-04-17 08:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_odb', models.FileField(null=True, upload_to='files')),
                ('file_compressed', models.FileField(null=True, upload_to='files')),
                ('job_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('remark', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('author', models.CharField(max_length=15)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[3456789]\\d{9}', message='请输入正确的手机号码')])),
                ('email', models.CharField(max_length=20, validators=[django.core.validators.EmailValidator(message='请输入正确的邮箱地址')])),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
