# Generated by Django 4.0.4 on 2022-04-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shareaccount',
            options={'ordering': ('share_job',)},
        ),
    ]
