# Generated by Django 3.2.13 on 2022-04-16 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[3456789]\\d{9}', message='请输入正确的手机号码')])),
                ('email', models.CharField(max_length=20, validators=[django.core.validators.EmailValidator(message='请输入正确的邮箱地址')])),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
