# Generated by Django 3.2.13 on 2022-04-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0002_delete_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Job',
        ),
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
