# Generated by Django 3.2.13 on 2022-04-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0002_alter_job_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-publish',)},
        ),
    ]
