# Generated by Django 3.2.13 on 2022-04-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
