# Generated by Django 3.2.13 on 2022-04-18 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_manage', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_manage_jobs', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_compressed',
            field=models.FileField(null=True, upload_to='files', verbose_name='原始料号压缩包'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_odb',
            field=models.FileField(null=True, upload_to='files', verbose_name='ODB++料号'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='料号名称'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remark',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='备注'),
        ),
    ]
