# Generated by Django 4.0.4 on 2022-08-01 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0003_layer_layer_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='层名称'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_file_type',
            field=models.CharField(choices=[('gerber274X', 'Gerber274-X'), ('gerber274D', 'Gerber274-D'), ('excellon2', 'Excellon2'), ('excellon1', 'Excellon1'), ('dxf', 'DXF'), ('else', '其它')], default='else', max_length=100, verbose_name='层文件类型'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_org',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='原始层名称'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('signal_outter', '外层'), ('signal_inner', '内层'), ('solder', '防焊'), ('silk', '丝印'), ('paste', '锡膏'), ('drill', '孔层'), ('rout', 'Rout'), ('slot', '槽孔'), ('else', '其它')], default='else', max_length=100, verbose_name='层类型'),
        ),
    ]
