# Generated by Django 4.0.4 on 2022-04-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0004_item_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
