# Generated by Django 4.0.4 on 2022-08-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0004_alter_layer_layer_alter_layer_layer_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file_compressed_org',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='原始文件'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_compressed',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='整理过的原始文件'),
        ),
    ]
