# Generated by Django 4.0.4 on 2022-05-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0005_remove_itemimage_item_delete_item_delete_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file_compressed',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='原始料号压缩包'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_odb',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='ODB++料号'),
        ),
    ]
