# Generated by Django 4.0.4 on 2022-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0005_job_file_compressed_org_alter_job_file_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '正式')], default='draft', max_length=10),
        ),
    ]
