# Generated by Django 4.0.4 on 2022-05-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0006_alter_job_file_compressed_alter_job_file_odb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shareaccount',
            name='slug',
        ),
    ]
