# Generated by Django 4.0.4 on 2022-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0006_layer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bool_layer_info',
            field=models.CharField(blank=True, choices=[('true', 'true'), ('false', 'false')], default='false', max_length=10, null=True, verbose_name='是否有层别信息'),
        ),
    ]
