# Generated by Django 4.0.4 on 2022-05-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_manage', '0007_remove_job_slug_remove_shareaccount_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_manage_jobs', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
