# Generated by Django 4.0.4 on 2022-05-08 05:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0009_alter_job_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AddField(
            model_name='job',
            name='from_object',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='料号来源'),
        ),
        migrations.AlterField(
            model_name='job',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_odb',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='料号（ODB++|EPS）'),
        ),
        migrations.AlterField(
            model_name='job',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '正式')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
