# Generated by Django 4.0.4 on 2022-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0010_alter_job_options_job_from_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file_odb_current',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='当前-EP-ODB++'),
        ),
        migrations.AddField(
            model_name='job',
            name='file_odb_g',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='G-ODB++'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_odb',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='EP-ODB++'),
        ),
    ]
