# Generated by Django 4.0.4 on 2022-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0011_job_file_odb_current_job_file_odb_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drill_excellon2_number_format_A',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='2', max_length=10, verbose_name='excellon2_format_A'),
        ),
        migrations.AddField(
            model_name='job',
            name='drill_excellon2_number_format_B',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='5', max_length=10, verbose_name='excellon2_format_B'),
        ),
        migrations.AddField(
            model_name='job',
            name='drill_excellon2_units',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM')], default='Inch', max_length=10, verbose_name='excellon2_units'),
        ),
        migrations.AddField(
            model_name='job',
            name='drill_excellon2_zeroes_omitted',
            field=models.CharField(choices=[('Leading', 'Leading'), ('Trailing', 'Trailing'), ('none', 'None')], default='Leading', max_length=10, verbose_name='excellon2_省零方式'),
        ),
        migrations.AddField(
            model_name='job',
            name='file_org_type',
            field=models.CharField(choices=[('gerber274X', 'Gerber274-X'), ('gerber274D', 'Gerber274-D'), ('odb++', 'ODB++'), ('else', '其它')], default='else', max_length=10, verbose_name='原始料号类型'),
        ),
        migrations.AddField(
            model_name='job',
            name='vs_result_ep',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('none', '未比对')], default='none', max_length=10, verbose_name='悦谱比图结果'),
        ),
        migrations.AddField(
            model_name='job',
            name='vs_result_g',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('none', '未比对')], default='none', max_length=10, verbose_name='G软件比图结果'),
        ),
    ]
