# Generated by Django 4.0.4 on 2022-08-04 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0011_alter_job_vs_result_ep_alter_job_vs_result_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vs_time',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='比对时间戳'),
        ),
        migrations.AddField(
            model_name='vs',
            name='vs_time',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='比对时间戳'),
        ),
    ]
