# Generated by Django 4.0.4 on 2022-07-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0012_job_drill_excellon2_number_format_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drill_excellon2_tool_units',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('Mils', 'Mils')], default='Mils', max_length=10, verbose_name='excellon2_tool_units'),
        ),
    ]
