# Generated by Django 4.0.4 on 2022-08-04 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0012_job_vs_time_vs_vs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='vs_time',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0)], verbose_name='比对时间戳'),
        ),
    ]
