# Generated by Django 4.0.4 on 2022-08-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0013_layer_vs_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='drill_excellon2_number_format_A',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='drill_excellon2_number_format_B',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='drill_excellon2_tool_units',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='drill_excellon2_units',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='drill_excellon2_zeroes_omitted',
        ),
        migrations.AddField(
            model_name='layer',
            name='number_format_A_ep',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('none', '未记录')], default='none', max_length=10, verbose_name='整数EP'),
        ),
        migrations.AddField(
            model_name='layer',
            name='number_format_A_g',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('none', '未记录')], default='none', max_length=10, verbose_name='整数G'),
        ),
        migrations.AddField(
            model_name='layer',
            name='number_format_B_ep',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('none', '未记录')], default='none', max_length=10, verbose_name='小数EP'),
        ),
        migrations.AddField(
            model_name='layer',
            name='number_format_B_g',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('none', '未记录')], default='none', max_length=10, verbose_name='小数G'),
        ),
        migrations.AddField(
            model_name='layer',
            name='tool_units_ep',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('Mils', 'Mils'), ('none', '未记录')], default='none', max_length=10, verbose_name='Tool_units_EP'),
        ),
        migrations.AddField(
            model_name='layer',
            name='tool_units_g',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('Mils', 'Mils'), ('none', '未记录')], default='none', max_length=10, verbose_name='Tool_units_G'),
        ),
        migrations.AddField(
            model_name='layer',
            name='units_ep',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('none', '未记录')], default='none', max_length=10, verbose_name='units_EP'),
        ),
        migrations.AddField(
            model_name='layer',
            name='units_g',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('none', '未记录')], default='none', max_length=10, verbose_name='units_G'),
        ),
        migrations.AddField(
            model_name='layer',
            name='zeroes_omitted_ep',
            field=models.CharField(choices=[('Leading', 'Leading'), ('Trailing', 'Trailing'), ('none', '未记录')], default='none', max_length=10, verbose_name='省零EP'),
        ),
        migrations.AddField(
            model_name='layer',
            name='zeroes_omitted_g',
            field=models.CharField(choices=[('Leading', 'Leading'), ('Trailing', 'Trailing'), ('none', '未记录')], default='none', max_length=10, verbose_name='省零G'),
        ),
    ]
