# Generated by Django 4.0.4 on 2022-07-29 03:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0013_job_drill_excellon2_tool_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='drill_excellon2_number_format_A',
        ),
        migrations.RemoveField(
            model_name='job',
            name='drill_excellon2_number_format_B',
        ),
        migrations.RemoveField(
            model_name='job',
            name='drill_excellon2_tool_units',
        ),
        migrations.RemoveField(
            model_name='job',
            name='drill_excellon2_units',
        ),
        migrations.RemoveField(
            model_name='job',
            name='drill_excellon2_zeroes_omitted',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('common', '普通板'), ('hdi', 'HDI'), ('led', 'LED板'), ('else', '其它')], default='common', max_length=10, verbose_name='料号类型'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_compressed',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='原始文件'),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_odb_current',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='最新-EP-ODB++'),
        ),
        migrations.CreateModel(
            name='EachJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='层名称')),
                ('layer_file_type', models.CharField(choices=[('gerber274X', 'Gerber274-X'), ('gerber274D', 'Gerber274-D'), ('excellon2', 'Excellon2'), ('excellon1', 'Excellon1'), ('dxf', 'DXF'), ('else', '其它')], default='else', max_length=10, verbose_name='层文件类型')),
                ('layer_type', models.CharField(choices=[('signal_outter', '外层'), ('signal_inner', '内层'), ('solder', '防焊'), ('silk', '丝印'), ('paste', '锡膏'), ('drill', '孔层'), ('rout', 'Rout'), ('slot', '槽孔'), ('else', '其它')], default='else', max_length=20, verbose_name='层类型')),
                ('drill_excellon2_units', models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM')], default='Inch', max_length=10, verbose_name='E2_units')),
                ('drill_excellon2_zeroes_omitted', models.CharField(choices=[('Leading', 'Leading'), ('Trailing', 'Trailing'), ('none', 'None')], default='Leading', max_length=10, verbose_name='E2省零')),
                ('drill_excellon2_number_format_A', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='2', max_length=10, verbose_name='E2_format_A')),
                ('drill_excellon2_number_format_B', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='5', max_length=10, verbose_name='E2_format_B')),
                ('drill_excellon2_tool_units', models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('Mils', 'Mils')], default='Mils', max_length=10, verbose_name='E2_tool')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_manage_layer', to='job_manage.job', verbose_name='料号名称')),
            ],
        ),
    ]
