# Generated by Django 4.0.4 on 2022-08-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0014_remove_layer_drill_excellon2_number_format_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vs',
            name='drill_excellon2_number_format_A',
        ),
        migrations.RemoveField(
            model_name='vs',
            name='drill_excellon2_number_format_B',
        ),
        migrations.RemoveField(
            model_name='vs',
            name='drill_excellon2_tool_units',
        ),
        migrations.RemoveField(
            model_name='vs',
            name='drill_excellon2_units',
        ),
        migrations.RemoveField(
            model_name='vs',
            name='drill_excellon2_zeroes_omitted',
        ),
    ]
