# Generated by Django 4.0.4 on 2022-07-29 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0014_remove_job_drill_excellon2_number_format_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachjob',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='备注'),
        ),
    ]
