# Generated by Django 4.0.4 on 2022-07-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0015_eachjob_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachjob',
            name='drill_excellon2_number_format_A',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('none', '未记录')], default='none', max_length=10, verbose_name='E2_format_A'),
        ),
        migrations.AlterField(
            model_name='eachjob',
            name='drill_excellon2_number_format_B',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('none', '未记录')], default='none', max_length=10, verbose_name='E2_format_B'),
        ),
        migrations.AlterField(
            model_name='eachjob',
            name='drill_excellon2_tool_units',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('Mils', 'Mils'), ('none', '未记录')], default='none', max_length=10, verbose_name='E2_tool'),
        ),
        migrations.AlterField(
            model_name='eachjob',
            name='drill_excellon2_units',
            field=models.CharField(choices=[('Inch', 'Inch'), ('MM', 'MM'), ('none', '未记录')], default='none', max_length=10, verbose_name='E2_units'),
        ),
        migrations.AlterField(
            model_name='eachjob',
            name='drill_excellon2_zeroes_omitted',
            field=models.CharField(choices=[('Leading', 'Leading'), ('Trailing', 'Trailing'), ('none', '未记录')], default='none', max_length=10, verbose_name='E2省零'),
        ),
    ]
