# Generated by Django 4.0.4 on 2022-07-29 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0016_alter_eachjob_drill_excellon2_number_format_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachjob',
            name='features_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(0)], verbose_name='物件数'),
        ),
    ]
