# Generated by Django 4.0.4 on 2022-07-29 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0017_eachjob_features_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachjob',
            name='features_count',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(0)], verbose_name='物件数'),
        ),
    ]
