# Generated by Django 4.0.4 on 2022-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_last_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_rule_status',
            field=models.CharField(choices=[('no', '否'), ('yes', '是')], default='no', max_length=10, verbose_name='客规'),
        ),
        migrations.AddField(
            model_name='project',
            name='factory_rule_status',
            field=models.CharField(choices=[('no', '否'), ('yes', '是')], default='no', max_length=10, verbose_name='厂规'),
        ),
    ]
