# Generated by Django 4.0.4 on 2022-05-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_manage', '0005_remove_itemimage_item_delete_item_delete_itemimage'),
        ('project', '0002_project_customer_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_job_work', to='job_manage.job', verbose_name='工作稿料号'),
        ),
    ]
