# Generated by Django 4.0.4 on 2022-04-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_customer_rule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_type',
            field=models.CharField(choices=[('create', '创建'), ('share', '分享')], default='create', max_length=10, verbose_name='工程来源'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
