# Generated by Django 4.0.4 on 2022-04-28 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('project', '0005_alter_project_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='factory_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_factory_rule', to='account.factoryrule', verbose_name='厂规'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_rule_status',
            field=models.CharField(blank=True, choices=[('no', '否'), ('yes', '是')], default='no', max_length=10, null=True, verbose_name='客规状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='factory_rule_status',
            field=models.CharField(blank=True, choices=[('no', '否'), ('yes', '是')], default='no', max_length=10, null=True, verbose_name='厂规状态'),
        ),
    ]
