# Generated by Django 4.0.4 on 2022-10-18 17:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
        ('taggit', '0005_mytag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='订单名称')),
                ('remark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注')),
                ('customer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='下单报价')),
                ('should_finish_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='应交付时间')),
                ('process_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='做单报价')),
                ('status', models.CharField(blank=True, choices=[('ToBeAccept', '未接单'), ('processing', '制作中'), ('EQing', 'EQ中'), ('ToBeCheck', '已提交待验收'), ('passed', '验收通过'), ('failed', '验收未通过')], default='ToBeAccept', max_length=10, null=True, verbose_name='订单状态')),
                ('process_times', models.IntegerField(blank=True, null=True, verbose_name='制作次数')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cam_order_type', models.CharField(choices=[('create', '创建'), ('share', '分享')], default='create', max_length=10, verbose_name='订单类型')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_author_user', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_customer_user', to=settings.AUTH_USER_MODEL, verbose_name='下单人')),
                ('last_update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_last_user', to=settings.AUTH_USER_MODEL, verbose_name='最后一次更新人')),
                ('process_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_process_user', to=settings.AUTH_USER_MODEL, verbose_name='做单人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_project', to='project.project', verbose_name='工程')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'cam_order',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='CamOrderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='订单流程名称')),
                ('remark', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='备注')),
                ('data', models.JSONField(blank=True, db_index=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_process_author_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('cam_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_process', to='order.camorder', verbose_name='CAM代工服务订单')),
            ],
            options={
                'db_table': 'cam_order_process',
                'ordering': ('-publish',),
            },
        ),
    ]
