# Generated by Django 4.0.4 on 2022-05-04 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_camorder_customer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camorder',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='订单名称'),
        ),
        migrations.AlterField(
            model_name='camorder',
            name='remark',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='备注'),
        ),
    ]
