# Generated by Django 4.0.4 on 2022-05-07 03:50

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_camorderprocess_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camorder',
            name='customer_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='Yuan', max_digits=14, null=True, verbose_name='下单报价'),
        ),
        migrations.AlterField(
            model_name='camorder',
            name='process_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='Yuan', max_digits=14, null=True, verbose_name='接单报价'),
        ),
    ]
