# Generated by Django 4.0.4 on 2022-05-07 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_alter_camorder_customer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camorder',
            name='process_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cam_order_process_user', to=settings.AUTH_USER_MODEL, verbose_name='接单人'),
        ),
    ]
