# Generated by Django 4.0.4 on 2022-05-07 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_camorder_process_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camorder',
            name='should_finish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='应交付时间'),
        ),
    ]
