# Generated by Django 3.2.13 on 2022-04-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '料号情况查询',
                'verbose_name_plural': '料号情况查询',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_org', models.FileField(upload_to='router_job_org', verbose_name='原始料号')),
                ('company_name', models.CharField(max_length=250, verbose_name='公司名称')),
                ('job_name_org', models.CharField(max_length=250, verbose_name='原始料号名称')),
                ('slug', models.SlugField(max_length=250, unique_for_date='receive_date')),
                ('receive_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='接受料号时间')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipe_status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='是否提供了参数')),
                ('remark', models.TextField(verbose_name='备注')),
                ('receive_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_org', to=settings.AUTH_USER_MODEL, verbose_name='料号负责人')),
            ],
            options={
                'verbose_name': '原始料号',
                'verbose_name_plural': '原始料号',
                'ordering': ('-receive_date',),
            },
        ),
        migrations.CreateModel(
            name='Pre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pre', models.FileField(upload_to='router_job_pre', verbose_name='前处理料号')),
                ('job_name_pre', models.CharField(max_length=250, verbose_name='前处理料号名称')),
                ('slug', models.SlugField(max_length=250, unique_for_date='pre_date')),
                ('pre_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='前处理料号时间')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pre_status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, verbose_name='是否完成了前处理')),
                ('remark', models.TextField(verbose_name='备注')),
                ('job_name_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_pre', to='gb.org', verbose_name='原始料号名称')),
                ('pre_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pre', to=settings.AUTH_USER_MODEL, verbose_name='前处理料号负责人')),
            ],
            options={
                'verbose_name': '前处理料号',
                'verbose_name_plural': '前处理料号',
                'ordering': ('-pre_date',),
            },
        ),
    ]
